### ISSUE TITLE
`marked` security vulnerability part II

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-docs#6]
wrt PR https://github.com/digitalbazaar/bedrock-docs/pull/5

A PR has been submitted to update `marked` subdependency here: https://github.com/raml-org/raml-js-parser-2/pull/800

It appears that `marked` is only used for documentation generation there which makes this a low priority.

**Comment by davidlehn** [comment]
I think this has been resolved upstream.
